// Generated by CoffeeScript 1.8.0
(function() {
  var Diaoyu;

  Diaoyu = angular.module('Diaoyu', []);

  Diaoyu.controller('MainCtrl', [
    '$scope', '$http', function($scope, $http) {
      return $scope.link = '/hi';
    }
  ]);

}).call(this);
